### ISSUE TITLE
A question about runtime

### ISSUE THREAD

**Issue by jcmharry** [christophstoeckl/FS-neurons#10]
Hi, I have read your excellent paper recently. The idea is very interesting. But there is a point that confused me. It seems that each layer has K steps. For one layer, only after K steps the neuron will output the sum of d(t)*z(t), is it correct?

**Comment by christophstoeckl** [comment]
Hi, 
thanks for the question. 

Yes, this is correct. As the next layer waits for all spikes of the previous layer to arrive anyway, this is the more convenient (and more efficient) way of implementing this functionality as it would be mathematically equivalent to sending the spikes to the next layer sequentially over time.

**Comment by jcmharry** [comment]
> Hi,
> thanks for the question.
> 
> Yes, this is correct. As the next layer waits for all spikes of the previous layer to arrive anyway, this is the more convenient (and more efficient) way of implementing this functionality as it would be mathematically equivalent to sending the spikes to the next layer sequentially over time.

Thanks for your quick reply. Can I think that the total run time of SNN equals (the number of layers)* K steps, as each layer should wait for K steps of the previous layer? And I have seen in the paper the K is 16 or 12. But the runtime of Resnet50 on cifar10 in the example is set as 500. How is it determined? Thanks.

**Comment by christophstoeckl** [comment]
You are right. 
For the ReLU function we used K=10 steps. hence the total number of time steps in an SNN would be 500. 

You can see this in the file called `fs_weights.py`.

**Comment by jcmharry** [comment]
> You are right.
> For the ReLU function we used K=10 steps. hence the total number of time steps in an SNN would be 500.
> 
> You can see this in the file called `fs_weights.py`.

Got it. Thanks very much.
