### ISSUE TITLE
What is the exact version of numpy, etc in requirements.txt?

### ISSUE THREAD

**Issue by tianyma** [christophstoeckl/FS-neurons#6]
Dear author, in the `requirements.txt`, what is the exact version of `h5py, Keras-Applications, numpy, scipy`?
```
h5py @ file:///tmp/build/80754af9/h5py_1593454119955/work
idna==2.10
Keras-Applications @ file:///tmp/build/80754af9/keras-applications_1594366238411/work
Keras-Preprocessing==1.1.0
Markdown==3.1.1
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1596233707986/work
protobuf==3.12.3
requests==2.24.0
scipy @ file:///tmp/build/80754af9/scipy_1592930510235/work
```

**Comment by christophstoeckl** [comment]
Thank you for pointing this out. 
The `requirements.txt` file has been updated.

**Comment by mervess** [comment]
Hello, just wanted to point out some misleading info in the repo regarding python packages.
The base code, including fs_*.py files, does not comply with tf-2.2 as claimed in the _readme_.
It should work with tf-1.14 according to _FS-neurons/requirements.txt_ , yet tf-2.x is recommended in the _tf-models_ directory which do not align with one another.
Additionally, _FS-neurons/requirements.txt_ is missing _matplotlib_ which is used in the demo.

Which version of the tf is the correct one? Also, which python version please?

**Comment by christophstoeckl** [comment]
Hi,

thanks for pointing this out.

For reproducing results the requirements.txt should be used, where the 
tf version is 1.14.

If one wants to convert a different model, tf 2.2 (as well as later 
versions) should also work.

The python version was 3.7, but I believe later versions should work 
fine as well.

I'm sorry about the inconvenience.

Best regards,
Christoph

**Comment by mervess** [comment]
Many thanks for the clarification Christoph. 

I've tried to build a new virtualenv based on _requirements.txt_ via Python 3.7. However, that caused some errors.
Some packages do not seem to exist anymore under pip and not compatible with Python 3.7 (for example -> https://pypi.org/project/Keras-Applications/#description).

Below are the first two errors I came across.
- Keras-Applications
```
ERROR: Could not find a version that satisfies the requirement Keras-Applications==1.1.2 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8)
ERROR: No matching distribution found for Keras-Applications==1.1.2
```
- mkl-fft
```
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.1.0 (from versions: 1.2.0, 1.3.0)
ERROR: No matching distribution found for mkl-fft==1.1.0
```
Afterall, I ended up building an env. around `pip install tensorflow==1.14.0`, and these are the Keras packages in my workspace:
```
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
```
The other packages also seem to be a little ahead in mine, but for your information and for others' whomever visits this topic, it seem to be working fine currently.

**Comment by christophstoeckl** [comment]
Thanks for letting me know.

It is unfortunate that some packages seem to not exist anymore.
There is also a capsule available, where the whole setup is conserved 
and all results can be reproduced: 
https://codeocean.com/capsule/7743810/tree , so maybe this is helpful as 
well.

Best regards,
Christoph
