### ISSUE TITLE
what does v_reg and z_reg mean?

### ISSUE THREAD

**Issue by matianyun** [christophstoeckl/FS-neurons#9]
Dear author, could you explain what does `v_reg` and `z_reg` mean in the while body of fs function? And while do you scale the input by 
```
 v_scaled = (v - T[t]) / (tf.abs(v) + 1)
```

**Comment by christophstoeckl** [comment]
`v_reg` and `z_reg` are tensors that can be useful when training an FS-neuron to use for regularization. 
Furthermore, `z_reg` can sometimes be used to count the number of spikes, if that is of interest. 

`v_scaled` is a trick to make sure that the custom gradient of the spike function is non-zero, which we found to be beneficial for training. 
Note that this scaling will not have an impact on whether or not a spike is triggered, as this only depends on the nominator of the fraction `(v - T[t])`, so it does not have an impact on the dynamics of the FS-neuron.

**Comment by matianyun** [comment]
clear, thank you for your reply.
